language: ruby

rvm:
  - 2.2.5
  - 2.3.1
  - 2.4.0
  - ruby-head

gemfile:
 - Gemfile

branches:
  only:
    - master
    - v0.12

before_install: gem update bundler
script: bundle exec rake test

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
